"""Over-the-air self-update from the public GitHub repo.

Each wake (WiFi already up, battery healthy) the device fetches a
tiny manifest. If the version differs from what's installed, it
downloads the changed files, verifies each by SHA-256 BEFORE
installing, swaps them in (main.py last), records the version, and
resets. Push to master -> the wall updates within the hour.

The manifest is generated by tools/make_ota_manifest.py and committed
alongside the code it describes.

Safety rails:
- every download verified against its manifest hash before install
- never touches boot.py
- skipped below 30% battery unless charging
- wrapped by the caller's try/except and the hardware watchdog
"""

import json
import os

try:
    import urequests as requests
except ImportError:
    import requests

RAW = ("https://raw.githubusercontent.com/"
       "Matthewjg95/todays-adventure/master/")
MANIFEST_URL = RAW + "ota_manifest.json"
VERSION_FILE = "ota_version.txt"
NEVER = ("boot.py",)


def _sha256(data):
    try:
        import uhashlib as hashlib
    except ImportError:
        import hashlib
    import binascii
    return binascii.hexlify(hashlib.sha256(data).digest()).decode()


def installed_version():
    try:
        with open(VERSION_FILE) as f:
            return f.read().strip()
    except OSError:
        return "none"


def _get(url, timeout=25):
    try:
        r = requests.get(url, timeout=timeout)
    except TypeError:
        r = requests.get(url)
    try:
        if r.status_code != 200:
            raise OSError("HTTP %d for %s" % (r.status_code, url))
        return r.content
    finally:
        r.close()


def _cleanup_staging(log=lambda m: None):
    """Remove orphaned .new files from an interrupted apply."""
    n = 0
    for d in ("/flash", "/flash/scenes/v3", "/flash/scenes/special"):
        try:
            names = os.listdir(d)
        except OSError:
            continue
        for name in names:
            if name.endswith(".new"):
                try:
                    os.remove(d + "/" + name)
                    n += 1
                except OSError:
                    pass
    if n:
        log("OTA: cleaned %d stale staged files" % n)


def _local_sha(path):
    try:
        with open(path, "rb") as f:
            return _sha256(f.read())
    except OSError:
        return None


def check_and_apply(log=lambda m: None):
    """Returns True if an update was installed (caller should reset)."""
    _cleanup_staging(log)
    manifest = json.loads(_get(MANIFEST_URL))
    version = manifest["version"]
    if version == installed_version():
        return False

    log("OTA: %s -> %s (%d files)"
        % (installed_version(), version, len(manifest["files"])))

    # Download + verify everything to .new BEFORE touching anything.
    staged = []
    for path, sha in manifest["files"].items():
        name = path.rsplit("/", 1)[-1]
        if name in NEVER:
            continue
        dest_probe = "/flash/" + manifest.get("dest", {}).get(path, path)
        if _local_sha(dest_probe) == sha:
            continue                 # already current: skip download
        data = _get(RAW + path)
        if _sha256(data) != sha:
            raise ValueError("OTA hash mismatch: %s" % path)
        dest = "/flash/" + manifest.get("dest", {}).get(path, path)
        _mkdirs(dest)
        with open(dest + ".new", "wb") as f:
            f.write(data)
        staged.append(dest)
    log("OTA: %d files staged and verified" % len(staged))
    if not staged:
        # everything already matched (e.g. a manual sync got here
        # first); just record the version
        with open(VERSION_FILE, "w") as f:
            f.write(version)
        return False

    # Swap in; main.py last so a power cut mid-swap leaves a bootable
    # mix of old main + new modules rather than a half-written main.
    staged.sort(key=lambda p: p.endswith("main.py"))
    for dest in staged:
        try:
            os.remove(dest)
        except OSError:
            pass
        os.rename(dest + ".new", dest)

    with open(VERSION_FILE, "w") as f:
        f.write(version)
    log("OTA: installed %s" % version)
    return True


def _mkdirs(path):
    parts = path.split("/")
    cur = ""
    for p in parts[:-1]:
        if not p:
            continue
        cur += "/" + p
        try:
            os.mkdir(cur)
        except OSError:
            pass
